datasource:
  mysql:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/shoppingmall?useUnicode=true?serverTimezone=Asia/Seoul&characterEncoding=utf8
      username: ENC(WtVtMmFZZbVQqIYLF3Elng==)
      password: ENC(wjWTVtQJFy4hqEvJtDRSGw==)
  mariadb:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/shoppingmall?useUnicode=true?serverTimezone=Asia/Seoul&characterEncoding=utf8
      username: ENC(WtVtMmFZZbVQqIYLF3Elng==)
      password: ENC(WtVtMmFZZbVQqIYLF3Elng==)

spring:
  config:
    activate:
      on-profile:
      - local
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  # r2dbc:
  #   url: mysql://localhost:3306/messenger?useUnicode=true&characterEncoding=utf8
  #   username: root
  #   password: root
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
jwt:
  auth:
    key: ENC(hFrp1I+S0acB47a5Oaoy9Q==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
