datasource:
  mysql:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: 
      username: 
      password: 
  mariadb:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: 
      username: 
      password: 

spring:
  config:
    activate:
      on-profile:
      - dev
  # data:
  #   redis:
  #     url: 
  #     password: 
  #     lettuce:
  #       pool:
  #         max-active: 5
logging:
  config: classpath:logback/logback-dev.xml